import java.util.Scanner;

/*
 4. You are given two strings s and t.
‌
String t is generated by random shuffling string s and then add one more letter at a random position.
‌
Return the letter that was added to t.
‌
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
‌
Example 2:
Input: s = "", t = "y"
Output: "y"
‌
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 */

public class FindExtraLetter {
    public static void main(String[] args) {
        Scanner scan = new Scanner(System.in);

        System.out.println("Enter First Word : ");
        String word1 = scan.nextLine();
        System.out.println("Enter Second Word : ");
        String word2 = scan.nextLine();

        char extraLetter = findExtraLetter(word1,word2);

        System.out.println("That Extra Letter : '"+extraLetter+"'");

        scan.close();
    }

    public static char findExtraLetter(String word1, String word2){
        int[] freq = new int[256];

        for(char c : word1.toCharArray()){
            freq[c]++;
        }
        for(char c : word2.toCharArray()){
            freq[c]++;
        }

        for(int i=0; i<freq.length; i++){
            if(freq[i] %2 != 0) return (char)i;
        }
        return '0';
    }
}
